apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-terminal-ez-setting
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: text
          name: index_notice_title
          label: 首页公告标题
          value: "Hello Terminal!"
        - $formkit: textarea
          name: index_notice_content
          label: 首页公告内容
          value: "一款 Terminal 风格的 Halo 主题."
        - $formkit: checkbox
          name: pixel_style
          label: 像素化风格
          help: 开启后, 将使用像素风格字体及图标
        - $formkit: checkbox
          name: show_toc
          label: 显示文章目录
          help: 开启后, 将在文章页面显示文章目录
        - $formkit: select
          name: default_schema_mode
          label: 默认模式
          value: "dark"
          options:
            - label: "暗模式"
              value: "dark"
            - label: "亮模式"
              value: "light"
        - $formkit: select
          name: dark_color_schema
          label: 暗色模式配色方案
          value: "dark"
          options:
            - label: "暗黑"
              value: "dark"
            - label: "亮色"
              value: "light"
            - label: "暗黄"
              value: "inkGold"
        - $formkit: select
          name: light_color_schema
          label: 亮色模式配色方案
          value: "light"
          options:
            - label: "暗黑"
              value: "dark"
            - label: "亮色"
              value: "light"
            - label: "暗黄"
              value: "inkGold"