apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-terminal-ez
  annotations:
    "store.halo.run/app-id": "app-ehsrxtbn"
spec:
  displayName: Terminal-EZ
  author:
    name: Erzbir
    website: https://erzbir.com
  description: 一款简洁复古的 Halo 主题 / A simple, retro theme for Halo
  logo: https://halo.run/logo
  website: https://www.halo.run/store/apps/app-ehsrxtbn
  repo: https://github.com/Erzbir/halo-theme-terminal.git
  issues: https://github.com/Erzbir/halo-theme-terminal/issues
  settingName: "theme-terminal-ez-setting"
  configMapName: "theme-terminal-ez-configMap"
  version: 1.2.0
  require: ">=2.8.0"
  license:
    - name: "MIT"
      url: "https://github.com/Erzbir/halo-theme-terminal/blob/main/LICENSE"
