apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-terminal-ez
spec:
  displayName: Terminal-EZ
  author:
    name: Erzbir
    website: https://github.com/Erzbir
  description: Halo 2.x 版本 Terminal 主题
  logo: https://halo.run/logo
  website: https://github.com/Erzbir/halo-theme-terminal
  repo: https://github.com/Erzbir/halo-theme-terminal.git
  settingName: "theme-terminal-ez-setting"
  configMapName: "theme-terminal-ez-configMap"
  version: 1.0.1
  require: ">=2.8.0"
